// <auto-generated />
using CrudHub.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudHub.WebApi.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrudHub.WebApi.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 55,
                            Name = "Semen Semyonovich",
                            Position = "Tokar",
                            Salary = 333m
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 45,
                            Name = "Aleksandr Prilykin",
                            Position = "Stolar",
                            Salary = 432m
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 28,
                            Name = "Evgen BadComediant",
                            Position = "Bloger",
                            Salary = 129202m
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 23,
                            Name = "Petro Vogyr",
                            Position = "Programmer",
                            Salary = 33231m
                        },
                        new
                        {
                            EmployeeId = 5,
                            Age = 34,
                            Name = "Karzen Viktorov",
                            Position = "Office manager",
                            Salary = 32421m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
